apiVersion: v2
name: cluster-api-provider-proxmox
description: A Helm chart for Cluster API provider proxmox
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.5.1"
annotations:
  cluster.x-k8s.io/provider: proxmox
  cluster.x-k8s.io/v1alpha3: v1alpha3
  cluster.x-k8s.io/v1alpha4: v1alpha4
  cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
  artifacthub.io/links: |
    - name: GitHub
      url: https://artifacthub.io/packages/helm/improwised/cluster-api-provider-proxmox
  artifacthub.io/maintainers: |
    - name: improwised
      email: rakshit@improwised.com
maintainers:
  - email: rakshit@improwised.com
    name: improwised
keywords:
  - capmox
  - cluster-api
  - proxmox
  - infrastructure
home: https://github.com/Improwised/charts/tree/main/charts/cluster-api-provider-proxmox
sources:
  - https://github.com/Improwised/charts
