annotations:
  truecharts.org/SCALE-support: "true"
  truecharts.org/catagories: |
    - homeautomation
  truecharts.org/grade: U
apiVersion: v2
appVersion: 2.0.15
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 11.1.2
description: Eclipse Mosquitto - An open source MQTT broker
home: https://truecharts.org/charts/stable/mosquitto
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mosquitto.png
keywords:
- mosquitto
- MQTT
- eclipse-iot
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: improwised
name: mosquitto
sources:
- https://github.com/truecharts/charts/tree/master/charts/stable/mosquitto
- https://github.com/eclipse/mosquitto
type: application
version: 8.0.12
