apiVersion: v2
appVersion: v13.4.1
description: Kubernetes Helm Chart for the lastest stable ERPNext branch
icon: https://raw.githubusercontent.com/frappe/design/master/logos/logo-2018/erpnext-logo-blue.svg
name: erpnext
type: application
version: 3.2.7
maintainers:
  - name: improwised
dependencies:
  - name: mariadb
    version: 9.3.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
